### ISSUE TITLE
Class logic test

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/University#15]
Please apply test for the below methods.

1. Generate welcome message i.e "Welcome to 'ClassName' dear student."
   * Test message
2. Generate a message when the class has reached the maximum size of capacity.
   * Test return value in both theories.
3. Generate a message when the class has still empty chair to get.
   * Test the manner of method in both cases.
4. Generate the area of each student according to the class area and its capacity.
   * Test return value in several theories.

**Comment by elighodsinezhad** [comment]
مدح دوست دااااااری
